#!/bin/bash

grupo=grupo08
NOMBREARCHIVO=$grupo.tgz

lista=""

TEMPORAL="TEMPORAL$RANDOM$RANDOM"

DIRECTORIO=$TEMPORAL/$grupo

mkdir -p $DIRECTORIO


mkdir -p $DIRECTORIO/arribos
mkdir -p $DIRECTORIO/oc
mkdir -p $DIRECTORIO/recibidos
mkdir -p $DIRECTORIO/rechazados
mkdir -p $DIRECTORIO/yarecibidos
mkdir -p $DIRECTORIO/aceptados
mkdir -p $DIRECTORIO/comandos/log
mkdir -p $DIRECTORIO/pruebas

for i in invini invonio startinvonio stopinvonio invreci remioc occtrl modulo_mover modulo_glog
do
    cp $i $DIRECTORIO/comandos/
    chmod +x $DIRECTORIO/comandos/$i
done

for i in generarCasosInvonio generarCasosInvreci generarCasosOcctrl generarCasosPruebaGeneral generarCasosRemioc
do
    cp $i $DIRECTORIO/pruebas/
    chmod +x $DIRECTORIO/pruebas/$i
    sed -i "s/\. prepararPruebas/grupo=\`pwd\`\/\.\./" $DIRECTORIO/pruebas/$i
done

cp README $DIRECTORIO/

mkdir release

cd $TEMPORAL

tar czf ../release/$NOMBREARCHIVO *

cd ..

rm -rf $TEMPORAL

