#! /bin/bash

# Salidas:  0 - OK
#           1 - Error de parámetros
#           2 - Archivo inexistente
#           3 - Directorio inexistente
#           4 - Sistema no inicializado

if [ -z "$SISTEMA_INICIALIZADO" ]
then
    echo "Error, no esta inicializado el sistema."
    return 4
fi

Mover(){
    local DUP="dup"
    local ESCRIBIR_LOG=""

    #Primero verificamos que la cantidad de parametros sea como minimo 2 (dos)
    if [ $# -le 1 ]
    then
	echo "Error: el comando necesita al menos 2 (dos) parametros"
	Glog "Mover" "Error: el comando necesita al menos 2 (dos) parametros" "E"
	return 1
    fi

    if [ $# -ge 3 ]
    then
	case "$3" in
	    "invreci") ESCRIBIR_LOG=1 ;;
	    "remioc")  ESCRIBIR_LOG=1 ;;
	esac
    fi

    #verificamos que exista el primer archivo
    if [ ! -e "$1" ]
    then
	echo "Error: El archivo $1 no existe."
	Glog "Mover" "Error: El archivo $1 no existe." "E"

	if [ ! -z $ESCRIBIR_LOG ]
	then
	    Glog "$3" "Error: El archivo $1 no existe." "E"
	fi

	return 2
    fi

    #Verificamos que origen y destino no sean iguales
    if [ "$1" = "$2" ]
    then
	Glog "Mover" "Origen y destino son iguales" "I"

	if [ ! -z $ESCRIBIR_LOG ]
	then
	    Glog "$3" "Origen y destino son iguales" "I"
	fi

	return 0
    fi

    #idem, pero para el caso que el segundo parámetro sea un directorio
    if [ -d "$2" ] 
    then
	local directorio=`dirname "$1"`
	if [ "$directorio" = "." ]
	then
	    directorio=`pwd`
	fi

	if [ "$directorio" = "$2" ]
	then
	    Glog "Mover" "Origen y destino son iguales" "I"

	    if [ ! -z $ESCRIBIR_LOG ]
	    then
		Glog "$3" "Origen y destino son iguales" "I"
	    fi
	    return 0
	fi
    fi

    directorio="${2%/*}"
    if [ ! -d  "$directorio" ]
    then
	echo "Error: El directorio $2 no existe."
	Glog "Mover" "Error: El directorio $2 no existe." "E"
	if [ ! -z $ESCRIBIR_LOG ]
	then
	    Glog "$3" "Error: El directorio $2 no existe." "E"
	fi
	return 3
    fi

    local archivo="${2##*/}"

    if [ "$archivo" = "" ]
    then
	archivo=`basename "$1"`
    fi 

    if [ -e "$directorio/$archivo" ]
    then
	#si existe, es un archivo duplicado
	if [ ! -d "$directorio/$DUP" ]
	then
	    #si no existe el directorio de duplicados, lo creo
	    rm -f "$directorio/$DUP" > /dev/null 2> /dev/null
	    mkdir "$directorio/$DUP"
	fi
	
	local numero=0
	local i=0
	for i in "$directorio/$DUP/$archivo".*
	do

	    local actual="${i##*.}"
	    if [ "$actual" != "*" ] 
	    then
		if [ $((10#$actual)) -ge $((10#$numero)) ]	
		then
		    numero=$(( 10#$actual + 1 ))
		fi
	    fi
	done
	numero=`printf "%.3i" $numero`
	mv "$1" "$directorio/$DUP/$archivo.$numero"

	Glog "Mover" "Se mueve el archivo $1"  "I"
	Glog "Mover" "a $directorio/$DUP/$archivo.$numero" "I"
	if [ ! -z $ESCRIBIR_LOG ]
	then
	    Glog "$3" "Se mueve el archivo $1"  "I"
	    Glog "$3" "a $directorio/$DUP/$archivo.$numero" "I"
	fi

    else
	mv "$1" "$directorio/$archivo"
	Glog "Mover" "Se mueve el archivo $1" "I"
	Glog "Mover" "a $directorio/$archivo" "I"
	if [ ! -z $ESCRIBIR_LOG ]
	then
	    Glog "$3" "Se mueve el archivo $1" "I"
	    Glog "$3" "a $directorio/$archivo" "I"
	fi
    fi

    return 0
}

export -f Mover
