#!/bin/bash

# Salidas:  0 - OK
#           1 - Error de parámetros
#           2 - Sistema no inicializado


if [ -z "$SISTEMA_INICIALIZADO" ]
then
    echo "Error, no esta inicializado el sistema."
    return 2
fi

Glog(){

    if [ $# -ne 3 ]
    then
	#Se requieren exactamente 3 parametros
	return 1
    fi

    local TIPO=""

    case $3 in
	[Ii]) TIPO="I";;
	[Ww]) TIPO="W";;
	[Ee]) TIPO="E";;
	[Ss][Ee]) TIPO="SE";;
	*) TIPO="I";;
    esac


    local DIRECTORIO="$grupo/comandos/log/"
    local NOMBRE_LOG="$DIRECTORIO/`basename $1`.log"

    mkdir -p "$DIRECTORIO"

    local FECHA=`getFechaYHora`
    
    local LINEA="$FECHA <$TIPO> $2"
    LINEA=`echo $LINEA | cut -c1-132` #limito la linea a 132 caracteres
    echo  $LINEA >> "$NOMBRE_LOG"

    return 0
}

export -f Glog
