#!/bin/bash

#Si NO esta inicializado el ambiente
if [ -z $SISTEMA_INICIALIZADO ]
then
    echo Error: El ambiente no fue inicializado
    exit 1
fi

# Verifica que exista un proceso invonio corriendo
estaCorriendo invonio
if [ $? -eq 0 ]
then
    desbloquearProceso invonio
else
    echo "No existe ningun proceso invonio corriendo."
fi

