#!/bin/bash

. invini
for archivo in $grupo/arribos/Prueba\ Individual\ Invonio/*
do	
  if [ -e "$archivo" ]  
  then
    cp "$archivo" "$grupo/arribos/"
  fi
done
rm -fr $grupo/arribos/Prueba\ Individual\ Invonio
echo Ejecutando Pruebas Del Comando Invonio... Aguarde Por Favor...
. invonio
