#!/bin/bash

grupo=`pwd`/Pruebas


#Elimino todo
rm -rf "$grupo"

#Creo la estructura de directorios

mkdir -p "$grupo"/arribos
mkdir -p "$grupo"/arribos/Prueba\ Individual\ Invonio
mkdir -p "$grupo"/oc
mkdir -p "$grupo"/recibidos
mkdir -p "$grupo"/rechazados
mkdir -p "$grupo"/yarecibidos
mkdir -p "$grupo"/aceptados
mkdir -p "$grupo"/comandos/log

#Copio los scripts al lugar correcto

for i in invini modulo_mover modulo_glog remioc invonio borrar ejecutar_pruebas_invonio invreci startinvonio stopinvonio occtrl
do
    cp $i "$grupo"/comandos/$i
    chmod +x "$grupo"/comandos/$i
done

#generacion de archivos de prueba

#############################################################
##############  ORDENES DE COMPRA  ##########################
#############################################################

#Es el archivo global de OC
#Nombre: ocgob.nn
#Formato : NumeroOrdenCompra;FechaOrdenCOmpra;CUITProveedor;EstadoOrdenCompra;UsuarioGrabacion;FechaYHoraGrabacion


cat <<EOF > "$grupo"/oc/ocgob.01
000000;20100101;00000000001;ABIERTA;LuCaS;01/01/2010 15:20:00
000001;20100102;00000000002;ABIERTA;VeRoNiCa;03/01/2010 08:15:01
000002;20100205;00000000003;ABIERTA;LuCiA;07/03/2010 03:33:33
123456;20100210;30324567820;ABIERTA;Matias;07/03/2010 03:38:35
123460;20100210;30324567891;ABIERTA;Matias;07/03/2010 03:38:35
123461;20100210;30324567891;ABIERTA;Matias;07/03/2010 03:38:35
EOF


#############################################################
#######  DESCRIPCIONES DE  ORDENES DE COMPRA  ###############
#############################################################

#Es el archivo de detalle de OC
#Nombre: ocdet.nn
#Formato : NumeroOrdenCompra;NroItem;CodigoProducto;CantidadTotal;CantidadRemanente;EstadodelItem;UsuarioGrabacion;FechaYHoraGrabacion


cat <<EOF > "$grupo"/oc/ocdet.01
000000;1;0000000001;2;2;ABIERTO;LuCaS;01/01/2010 15:20:00
000000;2;0000000002;4;4;ABIERTO;LuCaS;01/01/2010 15:20:00
000001;1;0000000003;5;5;ABIERTO;VeRoNiCa;03/01/2010 08:15:01
000002;1;0000000001;4;4;ABIERTO;LuCiA;07/03/2010 03:33:33
000002;2;0000000005;1;1;ABIERTO;LuCiA;07/03/2010 03:33:33
000002;3;0000000002;3;3;ABIERTO;LuCiA;07/03/2010 03:33:33
123456;1;F1A0900022;5;0;CERRADO;Matias;07/03/2010 03:33:33  
123456;2;CCC1900022;9;8;ABIERTO;Matias;07/03/2010 03:33:33  
123460;1;ABC1900022;2;2;ABIERTO;Matias;07/03/2010 03:33:33
123460;2;00A1900014;6;4;ABIERTO;Matias;07/03/2010 03:33:33
123461;1;00A1900FG5;4;4;ABIERTO;Matias;07/03/2010 03:33:33
123461;2;00A1900123;10;10;ABIERTO;Matias;07/03/2010 03:33:33
123461;3;00A19006LN;15;10;ABIERTO;Matias;07/03/2010 03:33:33
123461;4;00A19006LN;15;10;ABIERTO;Matias;07/03/2010 03:33:33 
EOF
							     #El ultimo caso seria
							     #Este caso esta para probar lo que sucede cuando las unidades entregadas superan la cantidad
							     #del remanente del detalle de la oc. Notar que el producto 00A19006LN esta duplicado porque 
							     #el remito indicara que se entregan mas unidades que el remanente de la primera aparicion del item en el detalle.

#############################################################
##########  REMITOS - Pruebas Individuales Invonio  #########
#############################################################

##Correctas
cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/11111111.19860919
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/22222222.19870706
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/33333333.19871014
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/44444444.19871024
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/55555555.19871205
EOF

#Incorrectas
cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/11.20100123
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/"12345678 20020721"
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/12222221.20101224
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/13434341.20100525
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/74187438.20200202
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/9999999999999999999.20050821
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/90487548.20060721000000000
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/abcdefgh.20031104
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/83273892.zzzzzzzz
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/74187839z18100503
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/88888888-20100229
EOF

cat <<EOF > "$grupo"/arribos/"Prueba Individual Invonio"/77777777-20080230
EOF

#############################################################
##############  REMITOS ACEPTADOS  ##########################
#############################################################

#Estos remitos son los que se usan para probar el comando remioc

#FORMATO de los remitos aceptados
#Nombre : <nro remito>.<nro oc>
#Contenido : FechaRemito,CodigoDeProducto,CantidadAEntregar,TiempoDescarga,Volumen,FechaEntrega,LugarEntrega,Transportista,Cuit,CompaniaAseguradora

cat <<EOF > "$grupo"/aceptados/00000001.000000.aproc
20100101;0000000001;2;10;12345.6;20100101;Algun_lugar;Desconocido;00000000001;Aseguradora
20100101;0000000002;3;7;98452.12;20100101;Algun_lugar;Desconocido;00000000001;Aseguradora
20100101;0000000002;1;2;01236.21;20100101;Algun_lugar;Desconocido;00000000001;Aseguradora
EOF

cat <<EOF > "$grupo"/aceptados/00000002.000001.aproc
20100103;0000000003;4;7;12345.6;20100103;Algun_lugar;Desconocido;00000000001;Aseguradora
EOF

cat <<EOF > "$grupo"/aceptados/00000003.000001.aproc
20100103;0000000003;1;3;01347.1;20100103;Algun_lugar;Desconocido;00000000001;Aseguradora
EOF

#Agregados
#1ero  Este caso no deberia pasar nada porque el estado del producto es cerrado.
#2do Este caso deberia dar una advertencia que recibo mas que el remanente. 
cat <<EOF > "$grupo"/aceptados/00000004.123456.aproc
20100103;F1A0900022;1;3;01347.1;20100103;Algun_lugar;Desconocido;30324567820;Aseguradora 
20100103;CCC1900022;15;3;01347.1;20100103;Algun_lugar;Desconocido;30324567820;Aseguradora 
EOF

#1ero Este producto lo deberia cerrar porque entro 2 productos y faltaban 2 productos
#Este producto lo deberia cerrar porque entrego 4 y faltaban 4

cat <<EOF > "$grupo"/aceptados/00000004.123460.aproc
20100103;ABC1900022;2;3;01347.1;20100103;Algun_lugar;Desconocido;30324567891;Aseguradora
20100103;00A1900014;4;3;01347.1;20100103;Algun_lugar;Desconocido;30324567891;Aseguradora
EOF

#Como consecuencia de lo anterior se deberia cambiar el estado de la Orden de Compra a CERRADA.

#1ero deberia quedar con un remanente.
#2do Deberia cerrarse el producto
#3ero Entrego mas productos que el remanente del primer detalle de la OC, deberia tener en cuenta la segunda aparicion del item en el detalle.

cat <<EOF > "$grupo"/aceptados/00000005.123461.aproc
20100103;00A1900FG5;3;3;01347.1;20100103;Algun_lugar;Desconocido;30324567891;Aseguradora 
20100103;00A1900123;10;3;01347.1;20100103;Algun_lugar;Desconocido;30324567891;Aseguradora
20100103;00A19006LN;12;3;01347.1;20100103;Algun_lugar;Desconocido;30324567891;Aseguradora 
EOF

#############################################################
##############  REMITOS RECIBIDOS  ##########################
#############################################################


#Nombre <nro remito><fecha de remito>
#Formato: NumeroOC,CodigoDeProductosaEntregar;CantidadAEntregar;TiempoDescarga;VolumenM3;FechaEntrega,LugarEntrega,Transportista;CUITProveedor;CompañiaAseguradora.

#Los siguientes remitos son para la prueba general del programa. Deberian generar los remitos aceptados que mencionamos previamente.

cat <<EOF > "$grupo"/recibidos/00000001.20100101
000000;0000000001;2;10;12345.6;20100101;Algun_lugar;Desconocido;00000000001;Aseguradora
000000;0000000002;3;7;98452.12;20100101;Algun_lugar;Desconocido;00000000001;Aseguradora
000000;0000000002;1;2;01236.21;20100101;Algun_lugar;Desconocido;00000000001;Aseguradora
EOF

cat <<EOF > "$grupo"/recibidos/00000002.20100215
000001;0000000003;4;7;12345.6;20100103;Algun_lugar;Desconocido;00000000002;Aseguradora
EOF

cat <<EOF > "$grupo"/recibidos/00000003.20100415
000001;0000000003;1;3;01347.1;20100103;Algun_lugar;Desconocido;00000000002;Aseguradora
EOF

cat <<EOF > "$grupo"/recibidos/00000004.20100215
123456;F1A0900022;1;3;01347.1;20100103;Algun_lugar;Desconocido;30324567820;Aseguradora
123456;CCC1900022;15;3;01347.1;20100103;Algun_lugar;Desconocido;30324567820;Aseguradora
123460;ABC1900022;2;3;01347.1;20100103;Algun_lugar;Desconocido;30324567891;Aseguradora
123460;00A1900014;4;3;01347.1;20100103;Algun_lugar;Desconocido;30324567891;Aseguradora
EOF


cat <<EOF > "$grupo"/recibidos/00000005.20100202
123461;00A1900FG5;3;3;01347.1;20100103;Algun_lugar;Desconocido;30324567891;Aseguradora
123461;00A1900123;10;3;01347.1;20100103;Algun_lugar;Desconocido;30324567891;Aseguradora
123461;00A19006LN;12;3;01347.1;20100103;Algun_lugar;Desconocido;30324567891;Aseguradora
EOF


#Estos remitos son usados para probar el modulo Invreci, no estan compaginados con el resto.

#1 Orden cerrada
#2 CUIT invalido
#3 Orden de compra inexistente
#4 formato inadecuado de registro
#5 Procesar bien
#6 Procesar bien
#7 Cuit invalido, orden cerrada, formato inadecuado, orden de compra inexiste.

#cat <<EOF > "$grupo"/recibidos/1.20100426
#123456;HHHHabcddd;15;30;10.5;20101225;CapitalFed.;TODOMUNDOSA;30324567891;Estafadores
#123457;HHHHabcddd;15;30;10.5;20101225;CapitalFed.;TODOMUNDOSA;30324567891;Estafadores
#123458;HHHHabcddd;15;30;10.5;20101225;CapitalFed.;TODOMUNDOSA;30324567891;Estafadores
#1234;HHHHabcddd;15;30;10.5201015;CapitalFed.;TODOMUNDOSA324567891;Estafadores
#123460;HHHHabcddd;15;30;10.5;20101225;CapitalFed.;TODOMUNDOSA;30324567891;Estafadores
#123461;HHHHabcddd;15;30;10.5;20101225;CapitalFed.;TODOMUNDOSA;30324567891;Estafadores
#123462;HHHHabcddd;15;30;10.5;20101225;CapitalFed.;TODOMUNDOSA;30324567891;Estafad
#EOF
