#!/bin/bash

grupo=`pwd`/Pruebas


#Elimino todo
rm -rf $grupo

#Creo la estructura de directorios

mkdir -p $grupo/arribos
mkdir -p $grupo/arribos/"Prueba Individual Invonio"
mkdir -p $grupo/oc
mkdir -p $grupo/recibidos
mkdir -p $grupo/rechazados
mkdir -p $grupo/yarecibidos
mkdir -p $grupo/aceptados
mkdir -p $grupo/comandos/log

#Copio los scripts al lugar correcto

for i in invini modulo_mover modulo_glog remioc invonio
do
    cp $i $grupo/comandos/$i
done

#generacion de archivos de prueba

#############################################################
##############  ORDENES DE COMPRA  ##########################
#############################################################

cat <<EOF > $grupo/oc/ocgob.01
000000;20100101;00000000001;ABIERTA;LuCaS;01/01/2010 15:20:00
000001;20100102;00000000002;ABIERTA;VeRoNiCa;03/01/2010 08:15:01
000002;20100205;00000000003;ABIERTA;LuCiA;07/03/2010 03:33:33
EOF


#############################################################
#######  DESCRIPCIONES DE  ORDENES DE COMPRA  ###############
#############################################################

cat <<EOF > $grupo/oc/ocdet.01
000000;1;0000000001;2;2;ABIERTO;LuCaS;01/01/2010 15:20:00
000000;2;0000000002;4;4;ABIERTO;LuCaS;01/01/2010 15:20:00
000001;1;0000000003;5;5;ABIERTO;VeRoNiCa;03/01/2010 08:15:01
000002;1;0000000001;4;4;ABIERTO;LuCiA;07/03/2010 03:33:33
000002;2;0000000005;1;1;ABIERTO;LuCiA;07/03/2010 03:33:33
000002;3;0000000002;3;3;ABIERTO;LuCiA;07/03/2010 03:33:33
EOF

#############################################################
##########  REMITOS - Pruebas Individuales Invonio  #########
#############################################################

##Correctas
cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/11111111.19860919
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/22222222.19870706
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/33333333.19871014
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/44444444.19871024
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/55555555.19871205
EOF

#Incorrectas
cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/11.20100123
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/"12345678 20020721"
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/12222221.20101224
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/13434341.20100525
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/74187438.20200202
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/9999999999999999999.20050821
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/90487548.20060721000000000
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/abcdefgh.20031104
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/83273892.zzzzzzzz
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/74187839z18100503
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/88888888-20100229
EOF

cat <<EOF > $grupo/arribos/"Prueba Individual Invonio"/77777777-20080230
EOF

#############################################################
##############  REMITOS ACEPTADOS  ##########################
#############################################################

cat <<EOF > $grupo/aceptados/00000001.000000.aproc
20100101;0000000001;2;10;12345.6;20100101;Algun lugar;Desconocido;00000000001;Aseguradora
20100101;0000000002;3;7;98452.12;20100101;Algun lugar;Desconocido;00000000001;Aseguradora
20100101;0000000002;1;2;01236.21;20100101;Algun lugar;Desconocido;00000000001;Aseguradora
EOF

cat <<EOF > $grupo/aceptados/00000002.000001.aproc
20100103;0000000003;4;7;12345.6;20100103;Algun lugar;Desconocido;00000000001;Aseguradora
EOF

cat <<EOF > $grupo/aceptados/00000003.000001.aproc
20100103;0000000003;1;3;01347.1;20100103;Algun lugar;Desconocido;00000000001;Aseguradora
EOF
