#!/bin/bash

grupo=`pwd`/Pruebas


#Elimino todo
rm -rf $grupo

#Creo la estructura de directorios

mkdir -p $grupo/arribos
mkdir -p $grupo/oc
mkdir -p $grupo/recibidos
mkdir -p $grupo/rechazados
mkdir -p $grupo/yarecibidos
mkdir -p $grupo/aceptados
mkdir -p $grupo/comandos/log

#Copio los scripts al lugar correcto

for i in invini Mover Glog remioc
do
    cp $i comandos/$i
done

#generacion de archivos de prueba

#############################################################
##############  ORDENES DE COMPRA  ##########################
#############################################################

cat <<EOF > $grupo/oc/ocgob.00
000000;20100101;00000000001;ABIERTA;LuCaS;01/01/2010 15:20:00
EOF

cat <<EOF > $grupo/oc/ocgob.01
000001;20100102;00000000002;ABIERTA;VeRoNiCa;03/01/2010 08:15:01
EOF

cat <<EOF > $grupo/oc/ocgob.02
000002;20100205;00000000003;ABIERTA;LuCiA;07/03/2010 03:33:33
EOF


#############################################################
#######  DESCRIPCIONES DE  ORDENES DE COMPRA  ###############
#############################################################

cat <<EOF > $grupo/oc/ocdet.00
000000;1;0000000001;2;2;ABIERTO;LuCaS;01/01/2010 15:20:00
EOF

cat <<EOF > $grupo/oc/ocdet.01
000000;2;0000000002;4;4;ABIERTO;LuCaS;01/01/2010 15:20:00
EOF

cat <<EOF > $grupo/oc/ocdet.02
000001;1;0000000003;5;5;ABIERTO;VeRoNiCa;03/01/2010 08:15:01
EOF

cat <<EOF > $grupo/oc/ocdet.03
000002;1;0000000001;4;4;ABIERTO;LuCiA;07/03/2010 03:33:33
EOF

cat <<EOF > $grupo/oc/ocdet.04
000002;2;0000000005;1;1;ABIERTO;LuCiA;07/03/2010 03:33:33
EOF

cat <<EOF > $grupo/oc/ocdet.05
000002;3;0000000002;3;3;ABIERTO;LuCiA;07/03/2010 03:33:33
EOF

#############################################################
##############  REMITOS ACEPTADOS  ##########################
#############################################################

cat <<EOF > $grupo/aceptados/00000001.000000.aproc
000000;0000000001;2;10;12345.6;20100101;Algun lugar;Desconocido;00000000001;Aseguradora
EOF

cat <<EOF > $grupo/aceptados/00000002.000000.aproc
000000;0000000002;3;7;98452.12;20100101;Algun lugar;Desconocido;00000000001;Aseguradora
EOF

cat <<EOF > $grupo/aceptados/00000003.000000.aproc
000000;0000000002;1;2;01236.2;20100101;Algun lugar;Desconocido;00000000001;Aseguradora
EOF
