#!/bin/bash

if [ -z "$grupo" ]
then
    echo "Error, no esta inicializado el sistema."
    return 0
fi

Glog(){
    return 0
    if [ $# -ne 3 ]
    then
	#Se requieren exactamente 3 parametros
	#TODO: ¿Grabar un log?
	return -1
    fi

    local TIPO=""

    case $3 in
	[Ii]) TIPO="I";;
	[Ww]) TIPO="W";;
	[Ee]) TIPO="E";;
	[Ss][Ee]) TIPO="SE";;
	*) TIPO="I";;
    esac


    local DIRECTORIO="$grupo/comandos/log/"
    local NOMBRE_LOG="$DIRECTORIO/`basename $1`.log"

    mkdir -p "$DIRECTORIO"

    local FECHA=`getFechaYHora`
    
    local LINEA= "$FECHA <$TIPO> $2"
    LINEA=`echo $LINEA | cut -c1-132` #limito la linea a 132 caracteres
    echo  $LINEA >> "$NOMBRE_LOG"

    return 0
}

export -f Glog
