#!/usr/bin/perl 

# Salidas:  0 - OK
#           1 - Sistema no inicializado
#           2 - Ya se encuentra corriendo otra instancia de occtrl
#           3 - No se encontró el archivo de ordenes de compra global
#           4 - No se encontró el archivo de detalles de ordenes de compra
#	    5 - Se encuentra corriendo remioc

use strict;
use Switch;

$0 = "occtrl";

my $SISTEMA_INICIALIZADO = $ENV{'SISTEMA_INICIALIZADO'};
my $grupo = $ENV{'grupo'};

if(!$SISTEMA_INICIALIZADO){
    print "El sistema no esta inicializado.\n";
    exit 1;
}

sub salir{
    #==============================================================
    #Desbloquear proceso.
    `/bin/bash -c "desbloquearProceso occtrl"`;
    #==============================================================

    exit $_;
}


#Busca el ultimo archivo de ordenes de compra 
sub buscarUltimaOC(){
    #$_[0] -> ocgob o ocdet
    my $INICIAL=01;
    my $NUMERO=0;
    my $otrogrupo = $grupo;
    $otrogrupo =~ s/ /\\ /g;
    my @CANDIDATOS = <$otrogrupo/oc/$_[0].*>;

    foreach (@CANDIDATOS){

	($NUMERO) = $_ =~ /\.([0-9]*)$/;
	
	if($NUMERO >= $INICIAL){
	    $INICIAL=$NUMERO;
	}
    }

    return $NUMERO;
}

#============================================================
#Si se encuentra corriendo el proceso remioc suspender la ejecucion

`/bin/bash -c "estaCorriendo remioc"`;

if ( $? == 0 ){
    print "Se esta ejecutando el comando remioc en este momento, se suspende la ejecucion.\n";
    exit 5;
}


#============================================================
#Si el proceso ya se encuentra corriendo suspender la ejecucion

`/bin/bash -c "estaCorriendo occtrl"`;

if ( $? == 0 ){
    print "Ya se encuentra corriendo un proceso occtrl.\n";
    exit 2;
}

`/bin/bash -c "bloquearProceso occtrl"`;
#=============================================================

my $NUMEROARCHIVO = &buscarUltimaOC("ocgob");
my $TOTAL = 0;
my $REMANENTE = 0;

open (ARCHIVO,'<',"$grupo/oc/ocgob.$NUMEROARCHIVO") or &salir(3);



#Formato programa -salida -all 
#        programa -salida -range mrangominimo rangomaximo
#	 programa -salida -single numero	

#Parseo de parametros
my $ARGC = @ARGV;
my $RANGOMINIMO = 0; 
my $RANGOMAXIMO = 999999;
my $ARCH = 0;
my $STD = 0;
my $PROXIMOARG;
if ($ARGC != 0){
    
    switch ($ARGV[0]) {
	case "-f" { open (ARCHIVOSALIDA , '>>', "$ARGV[1]"); $ARCH = 1; $PROXIMOARG = 2 ;}
	case -std { $STD = 1; $PROXIMOARG = 1;}
	case "-b" { $STD = 1; $ARCH = 1 ; open (ARCHIVOSALIDA , '>>', "$ARGV[1]") ; $PROXIMOARG = 2;}
	else  { print "El parametro correspondiente a la salida es invalido, se procesa con el parametro por defecto.\n";
		$STD = 1; $PROXIMOARG = 0;}
    }

    switch ($ARGV[$PROXIMOARG]){
	case -all { $RANGOMINIMO = 0; $RANGOMAXIMO = 999999;}
	case -range { $RANGOMINIMO = $ARGV[$PROXIMOARG+1]; $RANGOMAXIMO = $ARGV[$PROXIMOARG+2];}
	case -single { $RANGOMINIMO = $ARGV[$PROXIMOARG+1]; $RANGOMAXIMO = $ARGV[$PROXIMOARG+1];}
	else { print "El parametro correspondiente al rango de ordenes de compra es invalido, se procesa con el parametro por defecto.\n";
	      $RANGOMINIMO = 0; $RANGOMAXIMO = 999999;}
    }
    
}
else{
    $STD=1;
}


while (my $LINEA = <ARCHIVO>){
    (my $ESTADO) = $LINEA =~ "^[^;]*;[^;]*;[^;]*;([^;]*);";
    (my $NUMEROOC) = $LINEA =~ "^([^;]*);";
    (my $FECHAOC) = $LINEA =~ "^[^;]*;([^;]*);";
    (my $CUIT) = $LINEA =~ "^[^;]*;[^;]*;([^;]*);";
    (my $FECHAGRABACION) = $LINEA =~ "^[^;]*;[^;]*;[^;]*;[^;]*;[^;]*;([^;]*)";
    chomp $FECHAGRABACION;
    if ( $NUMEROOC >= $RANGOMINIMO && $NUMEROOC <= $RANGOMAXIMO ) { 
	$TOTAL=0;
	$REMANENTE=0;
	my $CUMPLIMIENTO=100;
	my $PENDIENTE=0;
	if ($ESTADO eq "ABIERTA") {
	    #Obtener las sumas totales de las cantidades de la orden de compra detallada.
	    $NUMEROARCHIVO = &buscarUltimaOC("ocdet");
	    open(ARCHIVO2, '<',"$grupo/oc/ocdet.$NUMEROARCHIVO") or &salir(4);
	    while (my $LINEA2 = <ARCHIVO2>){
		(my $NUMEROOCDETALLE) = $LINEA2 =~ "^([^;]*);";
		if ( $NUMEROOC == $NUMEROOCDETALLE ) {
		    (my $auxiliar) = $LINEA2 =~ "^[^;]*;[^;]*;[^;]*;([^;]*);";
		    $TOTAL+=$auxiliar;
		    ($auxiliar) = $LINEA2 =~ "^[^;]*;[^;]*;[^;]*;[^;]*;([^;]*);";
		    $REMANENTE += $auxiliar;
		}
		if ( $TOTAL != 0){
		    $CUMPLIMIENTO = 100 - (($REMANENTE) / $TOTAL) * 100;
		}
		$PENDIENTE = $REMANENTE;
		
	    }
	    close ARCHIVO2;
	}
	
	if ( $STD ) {
	    printf ( "\n" );
	    printf ( " Estado de la orden     : %s \n",$ESTADO);
	    printf ( " Orden de compra numero : %s \n",$NUMEROOC);
	    printf ( " Grado de cumplimiento  : %.2f \n",$CUMPLIMIENTO);
	    printf ( " Fecha de OC            : %s \n",$FECHAOC);
	    if ($ESTADO eq "CERRADA"){
		printf ( " Fecha de cierre        : %s \n",$FECHAGRABACION);
	    }else { printf (" Pendiente              : %i \n",$PENDIENTE);}
	    printf ( " Proveedor              : %s \n",$CUIT);
	    
	}
	if ( $ARCH ) {
	    printf (ARCHIVOSALIDA " Orden de compra numero : %s \n",$NUMEROOC);
	    printf (ARCHIVOSALIDA " Grado de cumplimiento  : %.2f \n",$CUMPLIMIENTO);
	    printf (ARCHIVOSALIDA " Fecha de OC            : %s \n",$FECHAOC);
	    if ($ESTADO eq "CERRADA"){
		printf (ARCHIVOSALIDA " Fecha de cierre        : %s \n",$FECHAGRABACION);
	    }else { printf (ARCHIVOSALIDA " Pendiente              : %i \n",$PENDIENTE);}
	    printf (ARCHIVOSALIDA " Proveedor              : %s \n",$CUIT);
	}
	

    }

}
close ARCHIVO;
close ARCHIVOSALIDA if ($ARCH);

&salir(0);
