#!/bin/bash

#Si NO esta inicializado el ambiente
if [ -z $SISTEMA_INICIALIZADO ]
then
    echo Error: El ambiente no fue inicializado
    exit 1
fi

# Verifico que no exista un proceso invonio corriendo
estaCorriendo invonio
if [ $? -ne 0 ]
then
    ./invonio&
else
    echo "Ya existe un proceso invonio corriendo."
fi

