#!/bin/bash

#Si NO esta inicializado el ambiente
if [ -z $SISTEMA_INICIALIZADO ]
then
    echo Error: El ambiente no fue inicializado
    exit 1
fi

# Verifica que exista un proceso invonio corriendo
estaCorriendo invonio
if [ $? -eq 0 ]
then
	LINE_PID=`grep "PID=" "$grupo/locks/.lock_invonio_corriendo"`
	PID=${LINE_PID:4}
	kill -15 $PID	
else
    echo "No existe ningun proceso invonio corriendo."
fi

